### ISSUE TITLE
Failed to attach: unexpectedly timed out while waiting for FIFO to establish

### ISSUE THREAD

**Issue by qibingbuso** [frida/frida-website#31]
I follow this page:http://www.frida.re/docs/android/
When i input 'frida-ps -R' I get the pid and NAME ,which is correct and what I wanted.

But next step, 'frida-trace -R -i open com.****'
I get the error result:Failed to attach: unexpectedly timed out while waiting for FIFO to establish

I don't know why :(

**Comment by simhigo** [comment]
I have same error :(

Do you solve this error?

**Comment by oleavr** [comment]
Fixed in the latest release (4.5.1).

**Comment by stevielavern** [comment]
Still have this issue on Frida 11.0.12 for some processes on linux ARM. 
Is there a way to troubleshoot the issue?

**Comment by oleavr** [comment]
@stevielavern This means that the target process is not able to open the FIFO that Linjector creates. The code it injects opens the FIFO [here](https://github.com/frida/frida-core/blob/30cf9a3df4dfbff7ec5e9331b845b457a142ffe5/src/linux/frida-helper-service-glue.c#L1459-L1462, so you could insert a jump instruction there to do an infinite loop, and then attach a debugger to it and look at `errno`.

**Comment by stevielavern** [comment]
I was able to troubleshoot the issue. It was actually a problem from the platform where I'm running Frida. There was a Linux Security Module blocking Frida, and that was visible in `dmesg` with the appropriate log level.  I manage to workaround the issue by adding the appropriate label to frida-gadget, and now I'm able to attach.
However, I have a similar issue when using frida-server because it creates a temporary linjector file that doesn't have the appropriate label. Is there a way not to create such temporary file when injecting with frida-server?

**Comment by stevielavern** [comment]
FYI there's an easy way to inject Frida-Gadget into a process without creating additional temporary files. Attach to it using `gdb` and run `p dlopen("/path/to/frida-gadget.so", 2)`. It requires your gdb setup to handle function calls correctly, which might or might not work depending on the platform and current stack trace.
